### ISSUE TITLE
Error: Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign

### ISSUE THREAD

**Issue by wuwei3** [lucadruda/iotc-java-device-client#4]
While building this project, I got error:

Generating E:\workspace_sensor\iotc-java-device-client\docs\com\github\lucadruda\iotc\device\exceptions\package-use.html...
Generating E:\workspace_sensor\iotc-java-device-client\docs\com\github\lucadruda\iotc\device\models\package-use.html...
Building index for all the packages and classes...
Generating E:\workspace_sensor\iotc-java-device-client\docs\overview-tree.html...
Generating E:\workspace_sensor\iotc-java-device-client\docs\index-all.html...
Generating E:\workspace_sensor\iotc-java-device-client\docs\deprecated-list.html...
Building index for all classes...
Generating E:\workspace_sensor\iotc-java-device-client\docs\allclasses-frame.html...
Generating E:\workspace_sensor\iotc-java-device-client\docs\allclasses-noframe.html...
Generating E:\workspace_sensor\iotc-java-device-client\docs\index.html...
Generating E:\workspace_sensor\iotc-java-device-client\docs\overview-summary.html...
Generating E:\workspace_sensor\iotc-java-device-client\docs\help-doc.html...
1 warning
[WARNING] Javadoc Warnings
[WARNING] E:\workspace_sensor\iotc-java-device-client\iotc-device-client\src\main\java\com\github\lucadruda\iotc\device\IoTCClient.java:81: warning: no @param for storage
[WARNING] public IoTCClient(String deviceId, String scopeId, IOTC_CONNECT authenticationType, Object options,
[WARNING] ^
[INFO] Building jar: E:\workspace_sensor\iotc-java-device-client\iotc-device-client\target\iotc-device-client-2.0.0-javadoc.jar
[INFO]
[INFO] --- maven-assembly-plugin:3.1.1:single (default) @ iotc-device-client ---
[INFO] Building jar: E:\workspace_sensor\iotc-java-device-client\iotc-device-client\target\iotc-device-client-2.0.0-jar-with-dependencies.jar
[INFO]
[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ iotc-device-client ---
'gpg.exe' is not recognized as an internal or external command,
operable program or batch file.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Azure IoTCentral Device Parent 2.0.0:
[INFO]
[INFO] Azure IoTCentral Device Parent ..................... SUCCESS [  0.138 s]
[INFO] Azure IoT Central Java Device Client ............... FAILURE [  9.607 s]
[INFO] Azure IoT Central Java Device Samples .............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.333 s
[INFO] Finished at: 2021-01-27T17:16:04+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project iotc-device-client: Exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :iotc-device-client

how to resolve?

**Comment by wuwei3** [comment]
I was building on windows 10, MAVEN3.7 , JDK1.8

**Comment by lucadruda** [comment]
what commands do you run when building?

**Comment by wuwei3** [comment]
> what commands do you run when building?

mvn install
mvn install iotc-java-device-client

both were getting the error.


BTW, is there any method to imitate send command from cloud to device in your code?
There are SendProperty ,SendTelemetry, but there is any method like call "SendCommand" which can imitate cloud send data to device?

And for the "SendProperty ", I have property named "firmwareVersion" in central, but I didn't get any message from your code:

 PropertiesCallback onProps = (IoTCProperty property) -> {
            System.out.println(String.format("Received property '%s' with value: %s", property.getName(),
                    property.getValue().toString()));
            property.ack("Property applied");
        };

I invoked the SendProperty, message can see in "Raw data" of device, but the listener didn't get the any message
what should I do?

**Comment by wuwei3** [comment]
Could you please tell me how to intimate firmware update with your code? many thanks.

**Comment by lucadruda** [comment]
Don't mix issues please. I've opened a separate one [(#6 )](https://github.com/lucadruda/iotc-java-device-client/issues/6) where you'll find response.

**Comment by lucadruda** [comment]
This issue is solved. Please pull latest code and run from root folder

_mvn -U clean install_

**Comment by wuwei3** [comment]
> mvn -U clean install

[INFO]
[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ iotc-device-client ---
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Azure IoTCentral Device Parent 2.0.0:
[INFO]
[INFO] Azure IoTCentral Device Parent ..................... SUCCESS [  0.245 s]
[INFO] Azure IoT Central Java Device Client ............... FAILURE [ 20.307 s]
[INFO] Azure IoT Central Java Device Samples .............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.129 s
[INFO] Finished at: 2021-01-30T20:29:29+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project iotc-device-client: Exit code: 2 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :iotc-device-client


sitll got error.

I noticed that you create new branch "develop",  which branch should run on? master or develop? this error is I met on the master branch

**Comment by lucadruda** [comment]
What's your pom.xml? You're still pulling old version here.

**Comment by wuwei3** [comment]
> What's your pom.xml? You're still pulling old version here.

     
![7](https://user-images.githubusercontent.com/46955295/106452516-f6ae8e80-64c2-11eb-8bdd-2d48e993c1d6.png)




it is still 2.0, very strange, I pulled the latest.
I will remove the local and re-clone the latest, it is not a issue, you could close the issue, many thanks
