### ISSUE TITLE
Device isn't showing in IoT Central

### ISSUE THREAD

**Issue by ynjacobs** [lucadruda/iotc-java-device-client#9]
Hi @lucadruda thanks again for this wonderful library.
I am trying to provision a device to IoT Central. I am using the SaS key example with group key.
I put in the credentials for `samples.config`:
```
deviceId = "testIt"
scopeId = "0neXXXX"
groupKey = "/LOd+XXXXXXXXXXXXXX=="
modelId = "dtmi:customXXXX:test36a;1"
```
I made the model to try and match the sample:
![Screenshot from 2021-03-10 10-33-13](https://user-images.githubusercontent.com/49129946/110654752-6a138200-818c-11eb-999c-e896716f034c.jpg)

But when I run the code I don't see the device having been made.
In the terminal I am getting:
```
[INFO] --------------< com.github.lucadruda:iotc-device-samples >--------------
[INFO] Building Azure IoT Central Java Device Samples 2.1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:exec (default-cli) @ iotc-device-samples ---
Welcome to IoTCentral
i am running
Exception: Illegal base64 character 22
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.540 s
[INFO] Finished at: 2021-03-10T10:28:39-05:00
[INFO] ------------------------------------------------------------------------
```
The error seems to throw at `client.Connect();` the second `System.out.println()` is not executing:
```
try {
	    System.out.println("i am running");
            client.Connect();
	    System.out.println("Am I running?");
            client.SendProperty(String.format("{\"propertyComponent\":{\"__t\":\"c\",\"prop1\":%d}}", 20));
```

Thanks so much!

**Comment by lucadruda** [comment]
you must remove quotes in your samples.config

**Comment by ynjacobs** [comment]
@lucadruda thank you, that was exactly what I needed!
